#!/bin/bash

#ReHo Metric
#std minus fast
3dttest++ -setA all_reho_std.nii.gz[0] all_reho_std.nii.gz[1] all_reho_std.nii.gz[2] all_reho_std.nii.gz[3] all_reho_std.nii.gz[4] all_reho_std.nii.gz[5] all_reho_std.nii.gz[6] all_reho_std.nii.gz[7] all_reho_std.nii.gz[8] all_reho_std.nii.gz[9] all_reho_std.nii.gz[10] all_reho_std.nii.gz[11] -setB all_reho_fast.nii.gz[0] all_reho_fast.nii.gz[1] all_reho_fast.nii.gz[2] all_reho_fast.nii.gz[3] all_reho_fast.nii.gz[4] all_reho_fast.nii.gz[5] all_reho_fast.nii.gz[6] all_reho_fast.nii.gz[7] all_reho_fast.nii.gz[8] all_reho_fast.nii.gz[9] all_reho_fast.nii.gz[10] all_reho_fast.nii.gz[11] -paired -prefix ttest_reho_std_minus_fast.nii.gz
#std minus ket
3dttest++ -setA all_reho_std.nii.gz[0] all_reho_std.nii.gz[1] all_reho_std.nii.gz[2] all_reho_std.nii.gz[3] all_reho_std.nii.gz[4] all_reho_std.nii.gz[5] all_reho_std.nii.gz[6] all_reho_std.nii.gz[7] all_reho_std.nii.gz[8] all_reho_std.nii.gz[9] all_reho_std.nii.gz[10] all_reho_std.nii.gz[11] -setB all_reho_ket.nii.gz[0] all_reho_ket.nii.gz[1] all_reho_ket.nii.gz[2] all_reho_ket.nii.gz[3] all_reho_ket.nii.gz[4] all_reho_ket.nii.gz[5] all_reho_ket.nii.gz[6] all_reho_ket.nii.gz[7] all_reho_ket.nii.gz[8] all_reho_ket.nii.gz[9] all_reho_ket.nii.gz[10] all_reho_ket.nii.gz[11] -paired -prefix ttest_reho_std_minus_ket.nii.gz
#fast minus ket
3dttest++ -setA all_reho_fast.nii.gz[0] all_reho_fast.nii.gz[1] all_reho_fast.nii.gz[2] all_reho_fast.nii.gz[3] all_reho_fast.nii.gz[4] all_reho_fast.nii.gz[5] all_reho_fast.nii.gz[6] all_reho_fast.nii.gz[7] all_reho_fast.nii.gz[8] all_reho_fast.nii.gz[9] all_reho_fast.nii.gz[10] all_reho_fast.nii.gz[11] -setB all_reho_ket.nii.gz[0] all_reho_ket.nii.gz[1] all_reho_ket.nii.gz[2] all_reho_ket.nii.gz[3] all_reho_ket.nii.gz[4] all_reho_ket.nii.gz[5] all_reho_ket.nii.gz[6] all_reho_ket.nii.gz[7] all_reho_ket.nii.gz[8] all_reho_ket.nii.gz[9] all_reho_ket.nii.gz[10] all_reho_ket.nii.gz[11] -paired -prefix ttest_reho_fast_minus_ket.nii.gz

#fALFF Metric
#std minus fast
3dttest++ -setA all_fALFF_std.nii.gz[0] all_fALFF_std.nii.gz[1] all_fALFF_std.nii.gz[2] all_fALFF_std.nii.gz[3] all_fALFF_std.nii.gz[4] all_fALFF_std.nii.gz[5] all_fALFF_std.nii.gz[6] all_fALFF_std.nii.gz[7] all_fALFF_std.nii.gz[8] all_fALFF_std.nii.gz[9] all_fALFF_std.nii.gz[10] all_fALFF_std.nii.gz[11] -setB all_fALFF_fast.nii.gz[0] all_fALFF_fast.nii.gz[1] all_fALFF_fast.nii.gz[2] all_fALFF_fast.nii.gz[3] all_fALFF_fast.nii.gz[4] all_fALFF_fast.nii.gz[5] all_fALFF_fast.nii.gz[6] all_fALFF_fast.nii.gz[7] all_fALFF_fast.nii.gz[8] all_fALFF_fast.nii.gz[9] all_fALFF_fast.nii.gz[10] all_fALFF_fast.nii.gz[11] -paired -prefix ttest_fALFF_std_minus_fast.nii.gz
#std minus ket
3dttest++ -setA all_fALFF_std.nii.gz[0] all_fALFF_std.nii.gz[1] all_fALFF_std.nii.gz[2] all_fALFF_std.nii.gz[3] all_fALFF_std.nii.gz[4] all_fALFF_std.nii.gz[5] all_fALFF_std.nii.gz[6] all_fALFF_std.nii.gz[7] all_fALFF_std.nii.gz[8] all_fALFF_std.nii.gz[9] all_fALFF_std.nii.gz[10] all_fALFF_std.nii.gz[11] -setB all_fALFF_ket.nii.gz[0] all_fALFF_ket.nii.gz[1] all_fALFF_ket.nii.gz[2] all_fALFF_ket.nii.gz[3] all_fALFF_ket.nii.gz[4] all_fALFF_ket.nii.gz[5] all_fALFF_ket.nii.gz[6] all_fALFF_ket.nii.gz[7] all_fALFF_ket.nii.gz[8] all_fALFF_ket.nii.gz[9] all_fALFF_ket.nii.gz[10] all_fALFF_ket.nii.gz[11] -paired -prefix ttest_fALFF_std_minus_ket.nii.gz
#fast minus ket
3dttest++ -setA all_fALFF_fast.nii.gz[0] all_fALFF_fast.nii.gz[1] all_fALFF_fast.nii.gz[2] all_fALFF_fast.nii.gz[3] all_fALFF_fast.nii.gz[4] all_fALFF_fast.nii.gz[5] all_fALFF_fast.nii.gz[6] all_fALFF_fast.nii.gz[7] all_fALFF_fast.nii.gz[8] all_fALFF_fast.nii.gz[9] all_fALFF_fast.nii.gz[10] all_fALFF_fast.nii.gz[11] -setB all_fALFF_ket.nii.gz[0] all_fALFF_ket.nii.gz[1] all_fALFF_ket.nii.gz[2] all_fALFF_ket.nii.gz[3] all_fALFF_ket.nii.gz[4] all_fALFF_ket.nii.gz[5] all_fALFF_ket.nii.gz[6] all_fALFF_ket.nii.gz[7] all_fALFF_ket.nii.gz[8] all_fALFF_ket.nii.gz[9] all_fALFF_ket.nii.gz[10] all_fALFF_ket.nii.gz[11] -paired -prefix ttest_fALFF_fast_minus_ket.nii.gz

#RSFA Metric
#std minus fast
3dttest++ -setA all_RSFA_std.nii.gz[0] all_RSFA_std.nii.gz[1] all_RSFA_std.nii.gz[2] all_RSFA_std.nii.gz[3] all_RSFA_std.nii.gz[4] all_RSFA_std.nii.gz[5] all_RSFA_std.nii.gz[6] all_RSFA_std.nii.gz[7] all_RSFA_std.nii.gz[8] all_RSFA_std.nii.gz[9] all_RSFA_std.nii.gz[10] all_RSFA_std.nii.gz[11] -setB all_RSFA_fast.nii.gz[0] all_RSFA_fast.nii.gz[1] all_RSFA_fast.nii.gz[2] all_RSFA_fast.nii.gz[3] all_RSFA_fast.nii.gz[4] all_RSFA_fast.nii.gz[5] all_RSFA_fast.nii.gz[6] all_RSFA_fast.nii.gz[7] all_RSFA_fast.nii.gz[8] all_RSFA_fast.nii.gz[9] all_RSFA_fast.nii.gz[10] all_RSFA_fast.nii.gz[11] -paired -prefix ttest_RSFA_std_minus_fast.nii.gz
#std minus ket
3dttest++ -setA all_RSFA_std.nii.gz[0] all_RSFA_std.nii.gz[1] all_RSFA_std.nii.gz[2] all_RSFA_std.nii.gz[3] all_RSFA_std.nii.gz[4] all_RSFA_std.nii.gz[5] all_RSFA_std.nii.gz[6] all_RSFA_std.nii.gz[7] all_RSFA_std.nii.gz[8] all_RSFA_std.nii.gz[9] all_RSFA_std.nii.gz[10] all_RSFA_std.nii.gz[11] -setB all_RSFA_ket.nii.gz[0] all_RSFA_ket.nii.gz[1] all_RSFA_ket.nii.gz[2] all_RSFA_ket.nii.gz[3] all_RSFA_ket.nii.gz[4] all_RSFA_ket.nii.gz[5] all_RSFA_ket.nii.gz[6] all_RSFA_ket.nii.gz[7] all_RSFA_ket.nii.gz[8] all_RSFA_ket.nii.gz[9] all_RSFA_ket.nii.gz[10] all_RSFA_ket.nii.gz[11] -paired -prefix ttest_RSFA_std_minus_ket.nii.gz
#fast minus ket
3dttest++ -setA all_RSFA_fast.nii.gz[0] all_RSFA_fast.nii.gz[1] all_RSFA_fast.nii.gz[2] all_RSFA_fast.nii.gz[3] all_RSFA_fast.nii.gz[4] all_RSFA_fast.nii.gz[5] all_RSFA_fast.nii.gz[6] all_RSFA_fast.nii.gz[7] all_RSFA_fast.nii.gz[8] all_RSFA_fast.nii.gz[9] all_RSFA_fast.nii.gz[10] all_RSFA_fast.nii.gz[11] -setB all_RSFA_ket.nii.gz[0] all_RSFA_ket.nii.gz[1] all_RSFA_ket.nii.gz[2] all_RSFA_ket.nii.gz[3] all_RSFA_ket.nii.gz[4] all_RSFA_ket.nii.gz[5] all_RSFA_ket.nii.gz[6] all_RSFA_ket.nii.gz[7] all_RSFA_ket.nii.gz[8] all_RSFA_ket.nii.gz[9] all_RSFA_ket.nii.gz[10] all_RSFA_ket.nii.gz[11] -paired -prefix ttest_RSFA_fast_minus_ket.nii.gz

#global_signal Metric
#std minus fast
3dttest++ -setA all_global_signal_std.nii.gz[0] all_global_signal_std.nii.gz[1] all_global_signal_std.nii.gz[2] all_global_signal_std.nii.gz[3] all_global_signal_std.nii.gz[4] all_global_signal_std.nii.gz[5] all_global_signal_std.nii.gz[6] all_global_signal_std.nii.gz[7] all_global_signal_std.nii.gz[8] all_global_signal_std.nii.gz[9] all_global_signal_std.nii.gz[10] all_global_signal_std.nii.gz[11] -setB all_global_signal_fast.nii.gz[0] all_global_signal_fast.nii.gz[1] all_global_signal_fast.nii.gz[2] all_global_signal_fast.nii.gz[3] all_global_signal_fast.nii.gz[4] all_global_signal_fast.nii.gz[5] all_global_signal_fast.nii.gz[6] all_global_signal_fast.nii.gz[7] all_global_signal_fast.nii.gz[8] all_global_signal_fast.nii.gz[9] all_global_signal_fast.nii.gz[10] all_global_signal_fast.nii.gz[11] -paired -prefix ttest_global_signal_std_minus_fast.nii.gz
#std minus ket
3dttest++ -setA all_global_signal_std.nii.gz[0] all_global_signal_std.nii.gz[1] all_global_signal_std.nii.gz[2] all_global_signal_std.nii.gz[3] all_global_signal_std.nii.gz[4] all_global_signal_std.nii.gz[5] all_global_signal_std.nii.gz[6] all_global_signal_std.nii.gz[7] all_global_signal_std.nii.gz[8] all_global_signal_std.nii.gz[9] all_global_signal_std.nii.gz[10] all_global_signal_std.nii.gz[11] -setB all_global_signal_ket.nii.gz[0] all_global_signal_ket.nii.gz[1] all_global_signal_ket.nii.gz[2] all_global_signal_ket.nii.gz[3] all_global_signal_ket.nii.gz[4] all_global_signal_ket.nii.gz[5] all_global_signal_ket.nii.gz[6] all_global_signal_ket.nii.gz[7] all_global_signal_ket.nii.gz[8] all_global_signal_ket.nii.gz[9] all_global_signal_ket.nii.gz[10] all_global_signal_ket.nii.gz[11] -paired -prefix ttest_global_signal_std_minus_ket.nii.gz
#fast minus ket
3dttest++ -setA all_global_signal_fast.nii.gz[0] all_global_signal_fast.nii.gz[1] all_global_signal_fast.nii.gz[2] all_global_signal_fast.nii.gz[3] all_global_signal_fast.nii.gz[4] all_global_signal_fast.nii.gz[5] all_global_signal_fast.nii.gz[6] all_global_signal_fast.nii.gz[7] all_global_signal_fast.nii.gz[8] all_global_signal_fast.nii.gz[9] all_global_signal_fast.nii.gz[10] all_global_signal_fast.nii.gz[11] -setB all_global_signal_ket.nii.gz[0] all_global_signal_ket.nii.gz[1] all_global_signal_ket.nii.gz[2] all_global_signal_ket.nii.gz[3] all_global_signal_ket.nii.gz[4] all_global_signal_ket.nii.gz[5] all_global_signal_ket.nii.gz[6] all_global_signal_ket.nii.gz[7] all_global_signal_ket.nii.gz[8] all_global_signal_ket.nii.gz[9] all_global_signal_ket.nii.gz[10] all_global_signal_ket.nii.gz[11] -paired -prefix ttest_global_signal_fast_minus_ket.nii.gz
